name: Deploy Passaporte Digital

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Configuração global de permissões para permitir a geração de token OIDC e deploy no Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Garante que apenas um deploy aconteça por vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate static page
        run: python src/generator.py

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

        # --- Notificações de Sucesso via telegram ---
      - name: Send Telegram Notification background
      if: success()
      run: |
      MESSAGE="Passaporte Digital LTD Atualizado!%0A%0AO site foi recompilado e publicado com sucesso no GitHub Pages.%0A%0A Acesse em: ${{steps.deployment.outputs.page_url}}"
      curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"\
      -d "chat_id=$ {{ secrets.TELEGRAM_CHAT_ID }}"\
      -d "text=${MESSAGE}"\
      -d "parse_mode=Markdonw"
